module AREA_VERIFICATOR_MODULE #(parameter BITS=10) (RST, POS_X, POS_Y, X, Y, WIDTH, HEIGHT, DIFF_X_COUNT, DIFF_Y_COUNT, IN_AREA_INDICATOR);

	input logic RST;
	input logic [BITS-1:0] POS_X, POS_Y, X, Y, WIDTH, HEIGHT;
	output logic IN_AREA_INDICATOR;
	output logic [BITS-1:0] DIFF_X_COUNT, DIFF_Y_COUNT;
	logic [BITS-1:0] X_PLUS_W, Y_PLUS_H, POSX_MIN_X, POSX_MIN_XW, POSY_MIN_Y, POSY_MIN_YH;
	logic CX, CY, GTX, LTXW, GTY, LTYH, DXB, DYB, X_AREA_INDICATOR, Y_AREA_INDICATOR;
	
	ADDER_MODULE #(BITS)
		X_PLUS_WIDTH (X, WIDTH, 1'b0, X_PLUS_W, CX),
		Y_PLUS_HEIGHT (Y, HEIGHT, 1'b0, Y_PLUS_H, CY);
		
	FULL_N_BITS_SUBTRACTOR_MODULE #(10) 
		POSX_GT_X  (X, POS_X, POSX_MIN_X, GTX),
		POSX_LT_XW (POS_X, X_PLUS_W, POSX_MIN_XW, LTXW),
		POSY_GT_Y  (Y, POS_Y, POSY_MIN_Y, GTY),
		POSY_LT_YH (POS_Y, Y_PLUS_H, POSY_MIN_YH, LTYH),
		DIFF_X     (POS_X, X, DIFF_X_COUNT, DXB),
		DIFF_Y     (POS_Y, Y, DIFF_Y_COUNT, DYB);
		
	_AND
		X_AREA_OR (GTX, LTXW, X_AREA_INDICATOR),
		Y_AREA_OR (GTY, LTYH, Y_AREA_INDICATOR);
		
	_AND AND (X_AREA_INDICATOR, Y_AREA_INDICATOR, IN_AREA_INDICATOR);
	
endmodule  